### ISSUE TITLE
Convert from google presentation links to actual .md files

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Talks#1]
Easier to maintain.

**Comment by WowSuchRicky** [comment]
How do we do this and then actually retain the format and whatnot? Or do we just want to retain content?

**Comment by LOZORD** [comment]
See my recent changes.

**Comment by LOZORD** [comment]
You create links like [this](http://example.com). You do this by wrapping the text in square brackets and the link in parentheses.

**Comment by katamaritaco** [comment]
I'm going to reopen. I think it'd be better for long term maintainability to get away from external links. Yeah, the slides may lose something (we can keep links as well), but it'd be nice to have a fully text .md for maintainability. Also, it gives you the ability to have text that you'd say but isn't on your slides (because slides full of text make us all sad).

tl:dr -> I think there is value in creating a 'transcript' of presentation. Doesn't have to be verbatim of course, but could be nice addition 8|

**Comment by spwilson2** [comment]
Just to clarify what Nick was thinking here since I needed it:
- Make previous presentations in .md format so they aren't (only) hosted in external google-docs
- In future presentations make this a standard
- In future presentations possibly create transcripts at the event

**Comment by katamaritaco** [comment]
Yeah. If we can download and archive the existing presentations here as well, that'd be great too. Basically, just want to future proof the talks

**Comment by LOZORD** [comment]
I think the easiest way would be to "print" as PDFs and then post those. I can convert and upload.

**Comment by LOZORD** [comment]
[uplvls_learn_to_program_with_ruby.pdf](https://github.com/UW-UPL/Talks/files/123471/uplvls_learn_to_program_with_ruby.pdf)

[intro_to_fp.pdf](https://github.com/UW-UPL/Talks/files/123473/intro_to_fp.pdf)

Here are mine!

**Comment by LOZORD** [comment]
Ok, all the pertinent ones should be in PDF form. LMK if there's any missing.
