### ISSUE TITLE
Cook's Python Talk

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Talks#10]
Pick a date, finalize content, put on the calendar on the website

**Comment by WowSuchRicky** [comment]
@MikeCook9994  plz

**Comment by MikeCook9994** [comment]
I know I'm working on it.

**Comment by MikeCook9994** [comment]
1) Reserved room
2) Created facebook event 

Will be finalizing the content this week and e-mailing Nikki Lemon to publicize the event.

**Comment by MikeCook9994** [comment]
Re opened until after the event (just in case things go wrong).
