### ISSUE TITLE
Fall 2016 Classes Talk

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Talks#11]
@Ricky54326 said he will help, but I think we said we want a junior to spearhead this.

**Comment by WowSuchRicky** [comment]
I'm happy to help but I'd prefer not to lead it due to lack of time.

Anyone else interested in doing so? @UW-UPL/coords

**Comment by katamaritaco** [comment]
I'd be happy to come and give some advice as well, but somebody with at least one semester left should do this.

**Comment by jdetter** [comment]
I probably wouldn’t be able to spearhead this as well but I would definitely help talk about a couple of the classes i've taken

**Comment by jdetter** [comment]
From facebook: So it looks like me and Michael Cook will be doing this, possibly with the help of Leo Rudberg if he's up for it (he's taken more of the CS math classes than me and Cook).

**Comment by MikeCook9994** [comment]
I've registered the room for the event and have created the facebook event. E-mails should be sent out to professors for information about their classes tomorrow or Tuesday at the latest.

The event will be the Monday after this coming (11th. At 5 PM)

**Comment by LOZORD** [comment]
Sure, I can help out.

**Comment by jdetter** [comment]
I sent the mailing list to Cook

**Comment by katamaritaco** [comment]
This is being worked on

**Comment by MikeCook9994** [comment]
Sent the e-mail tonight. Created the power point and added a template slide. Too late to do any work on it. @jdetter will add the list of course titles here later so you can reference it and let of know those of which you create slides for.

Anyone with this link can edit it:

https://docs.google.com/presentation/d/1jWfoA9itefad2TlZ_bFktIgrFuHzb1_mfYxHsyS9UvU/edit?usp=sharing

I CC'ed the upl-coords on the e-mail address so as those come in anyone will be able to see them.

**Comment by jdetter** [comment]
```
+-----------------------------------+---------+-------------------+
|           Course Name             |  Number |   Instructor      |
+-----------------------------------+---------+-------------------+
|  Introduction to Computation      |  CS202  |       TBA         |
|  Introduction to Descrete Math    |  CS240  |  Hasti, Beck      |
|  Introduction to Computer Eng     |  CS252  | Morrow OR Suhi    |
|  Introduction to Data Programming |  CS301  | Legault, Laura    |
|  Introduction to Programming      |  CS302  | Williams OR Dahl  | 
|  WES-CS Group Meeting             |  CS304  | NA                |
|  Digital System Fundamentals      |  CS352  | Morrow OR Krachey |
|  Machine Org. and Programming     |  CS354  | Skrentny, James   |
|  Introduction to Data Structures  |  CS367  | Deppler, Debra    |
|  C++ for Java Programmers         |  CS368  |        TBA        |
|  Learning a Programming Lang.     |  CS368  |        TBA        |
|  Matlab Programming               |  CS368  |        TBA        |
|  Introducing Computer Sci to K-12 |  CS402  | Arpaci, Andrea    |
|  Introduction to Num. Methods     |  CS412  | Ron, Amos         |
|  Introduction to Combinatorial Op |  CS425  | Del Pia, Alberto  |
|  Introduction to Cryptography     |  CS435  | Jha, Somesh       |
|  Introduction to Combinatorics    |  CS475  | Terwilliger, Paul |
|  Software Engineering             |  CS506  | Lewis-Williams    |
|  Numerical Analysis               |  CS514  | Li, Qin           |
|  Introduction to Theory of Comp.  |  CS520  | Cai, Jin-yi       |
|  Introduction to Optimization     |  CS524  | Ferris, Michael   |
|  Linear Programming Methods       |  CS525  | Yin, Jun          |
|  Theory and Applications of Patt. |  CS532  | Lessard, Laurent  |
|  Image Processing                 |  CS533  |     TBA??         |
|  Computational Photography        |  CS534  | Dyer, Chuck       |
|  Introduction to Programming Lang.|  CS536  | D'antoni, Loris   |
|  Introduction to Operating Sys.   |  CS536  | Arpaci, Andrea    |
|  Introduction to Artificial Intel |  CS540  | Zhu, Jerry OR Shavlik, Jude
|  Introduction to Computer Arch    |  CS552  | Hu, Yu            |
|  Computer Graphics                |  CS559  | Sifakis, Eftychios|
|  Database Management Systems      |  CS564  | Koutris, Paris OR Shatdal, Ambu
|  Introduction to Bioinformatics   |  CS576  | Dewey, Colin      |
|  Introduction to Algorithms       |  CS577  | Bach, Eric        |
|  Virtual Reality                  |  CS579  | Ponto, Kevin      |
|  Data Science                     |  CS638  | Doan, An          |
```

**Comment by WowSuchRicky** [comment]
CS564

A V O I D  L I K E  T H E  P L A G U E
V
O
I
D

L
I
K
E

T
H
E

P
L
A
G
U
E

**Comment by LOZORD** [comment]
@MikeCook9994 Did you create this with the UPL Google account?

**Comment by LOZORD** [comment]
@MikeCook9994 feel free to close this issue once you've taken care of the following:
- Add PDF version to the `archive/` directory
- Duplicate presentation and add to the UPL Google Drive account
