### ISSUE TITLE
UPL Games II writeup 

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Talks#14]
http://gph.is/16CVNEz

**Comment by katamaritaco** [comment]
Yeah I've been slowly hashing this out. Was going to go ham on it when school is finished :camel:

**Comment by LOZORD** [comment]
:pig: :ok_hand:

**Comment by spwilson2** [comment]
:camel:

**Comment by katamaritaco** [comment]
Yeah still working on this one :camel:

**Comment by LOZORD** [comment]
🐫 ?

**Comment by katamaritaco** [comment]
Working on it :camel:

**Comment by spwilson2** [comment]
:camel:

**Comment by LOZORD** [comment]
🐫

**Comment by spwilson2** [comment]
:camel:

**Comment by spwilson2** [comment]
:dromedary_camel: or should we just close at this point?

**Comment by MikeCook9994** [comment]
Honestly, just close it as this point. No one who participated would care.

**Comment by katamaritaco** [comment]
Is 90% done just forgot about it. Can finalize over Thanksgiving

Get Outlook for Androidhttps://aka.ms/ghei36

On Thu, Nov 17, 2016 at 2:30 PM -0600, "Sean Wilson" <notifications@github.com<mailto:notifications@github.com>> wrote:

? or should we just close at this point?

##

**Comment by LOZORD** [comment]
F I N A L L Y 👺

**Comment by LOZORD** [comment]
R I P ☠️
