### ISSUE TITLE
Review python talk slides

### ISSUE THREAD

**Issue by spwilson2** [UW-UPL/Talks#16]
Some info is slightly off or python2/3 specific such as: 
- integer/float division
- string mutability

**Comment by spwilson2** [comment]
@MikeCook9994 Could I get comment or edit permission?

**Comment by MikeCook9994** [comment]
I might have given it to you? The mobile app seems off.

**Comment by spwilson2** [comment]
Hmm, doesn't look like I have edit perms.

**Comment by spwilson2** [comment]
Alright I made some changes and a few comments, overall looked great though. I put comments for things that I couldn't easily change since they were either related to pictures or suggestions for additional information. I'll hand you the issue @MikeCook9994 to do what you want with it.

**Comment by MikeCook9994** [comment]
Noooooo don't create an issue....

**Comment by LOZORD** [comment]
Can we close this? @MikeCook9994

**Comment by LOZORD** [comment]
🐫
