### ISSUE TITLE
Add Leo's Haskell Talk

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Talks#3]

**Comment by LOZORD** [comment]
How do you want me to provide it? Just the slideshow and gist?

**Comment by LOZORD** [comment]
Google Slides slideshow:

https://docs.google.com/presentation/d/1xxfZseaQncqUq3UHGbW1LeTmNsg9Voun_uDWjJf2J3I/edit?usp=sharing

GitHub Gist w/ section from @mtolly 

https://gist.github.com/LOZORD/9d23396e4206a5b1cb02

**Comment by katamaritaco** [comment]
I added to talks
