### ISSUE TITLE
Update links to the new UPL website

### ISSUE THREAD

**Issue by spwilson2** [UW-UPL/Talks#5]
There might be a few links within the presentations to the old upl (@cs.wisc.edu) - change these to the github hosted site. (For instance in Leo's Haskell Talk)

**Comment by LOZORD** [comment]
Wouldn't this be fixed by the [redirect](https://github.com/UW-UPL/uw-upl.github.io/issues/45)?

**Comment by katamaritaco** [comment]
I don't think so, since links might have different paths regardless.

**Comment by LOZORD** [comment]
Ah true! Should I convert all the presentations, or just cut b8 and start over with the `.md` files?

**Comment by katamaritaco** [comment]
Up to you. There might be a conversion program already made as well - there is definitely one to convert .md to .pdf...

**Comment by LOZORD** [comment]
I can probably do everything faster by hand. And yeah, I'll take care of this. I can do all the presentations unless @Ricky54326 or @MarshMue want to do their own.

**Comment by LOZORD** [comment]
I'm going to close this. If a link is broken, we can make issues _ad hoc_.
