### ISSUE TITLE
Anybody opposed?

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Talks#8]
So I was thinking we add our misc. and inactive projects here (unless they're significant on their own). For example, I'd like to move the gofish and rust-dist-sys into here (and interviewprep next semester). I'll do it shortly unless people are opposed

**Comment by LOZORD** [comment]
I think it might be good to keep interview stuff separated in their own repos so that this repo doesn't get too bloated. Inactive projects might be good in a "Public Archives" repo.

**Comment by LOZORD** [comment]
:camel: cruft?

**Comment by katamaritaco** [comment]
As for inactive projects: I'd say if there is no progress for a long time, ask the original own and remove the repo. If there is progress, just leave it there for now (or create a 'groupprojects' repo and throw them in there).

For Interview stuff: I think they should go in there once they are done - aka once all answers have at least one solution. People can still add solutions, but it'd be within here. I think it is good to have in talks because: 1) the event was actually a talk 2) keeps the UW-UPL organization less cluttered, and 3) promotes the 'talks' page more.

What does everybody else think?

**Comment by LOZORD** [comment]
We can discuss this at the meeting.

**Comment by LOZORD** [comment]
Solution: Instead of bloating the Talks repo, we decided to create an InterviewPrep repo that contains subdirectories of **all** interview prep questions and solutions.

**Comment by katamaritaco** [comment]
Done. I'm moving everthing into here:
https://github.com/UW-UPL/UPLInterviewPrep
:camel:
